### ISSUE TITLE
How to output to DAC board

### ISSUE THREAD

**Issue by kzts** [iron76/beaglebone-black-yarp#5]
Now, do we have any way to output to DAC board using codes included in this `beaglebone-black-yarp`?
Should I add any codes here, if I want to read all sensors with our robot?

**Comment by iron76** [comment]
Yes, the code is already in place. I need to do some final tests in Tokyo but the code in the repository already talks to the DAC boards via SPI connection. If you want to do some tests on your own please notice that the main communication routines is implemented in the function `setRefOutput`, whose code is available here https://github.com/iron76/beaglebone-black-yarp/blob/master/src/modules/athleteInterface/src/BeagleBoneInputOutput.cpp#L226. Configuration of the pins via configuration file (yet to be tested) is on a different branch named `gpio_from_config_file`. In the `master` branch instead  configuration of pins is defined with macros (https://github.com/iron76/beaglebone-black-yarp/blob/master/src/modules/athleteInterface/src/BeagleBoneInputOutput.cpp#L12-L27).

**Comment by kzts** [comment]
Thank you for your advice. I want to do some tests using DAC board.

I did make following `beaglebone-black-yarp/src/modules/athleteInterface/README.TXT` 
and I got following error messages.

```
Linking CXX executable run_athletebot
/usr/bin/ld: cannot find -lbbbiommap
collect2: error: ld returned 1 exit status
make[2]: *** [run_athletebot] Error 1
make[1]: *** [CMakeFiles/run_athletebot.dir/all] Error 2
make: *** [all] Error 2
```

how can I get a library, `bbbiommap`?

**Comment by iron76** [comment]
Is the `BBB_YARP_DIR` environment variable properly defined? Please check by running `echo $BBB_YARP_DIR`. If it is then execute:

```
cd $BBB_YARP_DIR/beaglebone-black-yarp/build
cmake .. -DCMAKE_INSTALL_PREFIX:PATH=$BBB_YARP_DIR/bin
make
sudo make install
```

**Comment by kzts** [comment]
I run `echo $BBB_YARP_DIR` and I got `/home/bbb-user/Code`.
I executed your instraction and instalation has done without error.
I run make again in `beaglebone-black-yarp/src/modules/athleteInterface/build`
but I got same error messages. Is following my setting wrong?
Which directory should I select as `BBIO_LIBRARY`?

```
 BBIO_INCLUDE                     /home/bbb-user/Code/beaglebone-black-yarp/src/libraries/BBBIOlib/BBBio_lib
 BBIO_LIBRARY                     /home/bbb-user/Code/BBBIOlib                                       
 CMAKE_BUILD_TYPE                                                                                    
 CMAKE_INSTALL_PREFIX             /home/bbb-user/Code/bin                                            
 DISABLE_IO                       OFF                                                                
 ENABLE_DEBUG                     OFF                                                                
 ENABLE_athletebot                TRUE                                                               
 GPIO_INCLUDE                     /home/bbb-user/Code/beaglebone-black-yarp/src/libraries/BeagleBone-
 GPIO_LIBRARY                     /usr/local/bin/libgpiommap.a                                       
 YARP_DIR                         /home/bbb-user/Code/bin/lib/YARP    
```

**Comment by iron76** [comment]
I spotted a problem: you have a previously installed library that should be removed. Please delete the file /usr/local/bin/libgpiommap.a  and re-run the all process. This should fix the issue. You should not run make from `beaglebone-black-yarp/src/modules/athleteInterface/build` but only from `$BBB_YARP_DIR/beaglebone-black-yarp/build`. Also try to understand where the executable is located trying to run `which run_athletebot`.

**Comment by kzts** [comment]
I deleted the file, run make from `$BBB_YARP_DIR/beaglebone-black-yarp/build`, executed it successfully, understood that the executable is in `/home/bbb-user/Code/bin/bin/run_athletebot
` running `which run_athletebot`.  
But I still have a question. How do I use the function`setRefOutput`?
Should I write a code, or use any command?

**Comment by iron76** [comment]
There is a command line tool that you can use at first to check that things work properly. It is called `simpleClient`. Just run:

```
simpleClient --robot athletebot --part torso
```

Then you type `help` to see the list of commands. At present I only implemented the commands to set the voltage output for channel 0:

```
set out 0 50
```

The range of outputs (in the example above 50) should be between 0 and 90.

**Comment by kzts** [comment]
`simpleClient` worked happily! Thank you very much! :)
I have another quaetion for the next step. 
How do I make time series of output value?

**Comment by iron76** [comment]
Sorry for the late reply (for some reason I was not notified via email). To send time series you can try to modify the simple tutorial `motorControlBasic` that you can download from here https://github.com/robotology/icub-tutorials.git. Instead of opening an `IPositionControl` interface you need to open a `IOpenLoopControl` and cyclically calling the `setRefOutput` with different values.

**Comment by iron76** [comment]
@kzts could you please do the very same tests (i.e. testing the DAC) but switching to the other branch `gpio_from_config_file`? I made some important changes and I wanted to test them but I am not in Todai and I will not be for a week or so. Also you can ask one of your student to do the test (I don't have the github account of the one that came to me yesterday asking and willing to do some tests).

**Comment by kzts** [comment]
OK! I'll do the test. Which file?

**Comment by iron76** [comment]
you should test the run_athletebot application (both potentiometer reading and valve commands). The procedure is the usual described here (https://github.com/iron76/beaglebone-black-yarp) but after the command `git clone https://github.com/iron76/beaglebone-black-yarp.git` you should do:

```
cd $BBB_YARP_DIR
git checkout gpio_from_config_file
```

Then no other changes should be applied to the procedure.

**Comment by kzts** [comment]
OK! I'll try it!

**Comment by kzts** [comment]
I needed

```
cd $BBB_YARP_DIR/beaglebone-black-yarp/
```

**Comment by kzts** [comment]
I needed
```
cd $BBB_YARP_DIR/beaglebone-black-yarp/
```

**Comment by kzts** [comment]
I commanded

```
$BBB_YARP_DIR/beaglebone-black-yarp/scripts/init_all.sh
```

And I got following messages.
Can I ignore them?

```
Loading the can-bus ...
Cannot find device "can0"
can0: ERROR while getting interface flags: No such device
Setting the GPIO properties  ...
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
Adding current user to dialout (to read serial) ...
The user `bbb-user' is already a member of `dialout'.
Scritp terminated!
```

**Comment by kzts** [comment]
In YARP module manager, I found status of module `run_athletebot` was `running` but `robotinterface` and `yarpdev` were `stopped`. Can I ignore them?

**Comment by iron76** [comment]
Yes, you can ignore these errors. Were you able to set the output voltage?

**Comment by kzts** [comment]
Yes I could do it successfully!

By the way, how can I read data of a potentio meter from ADC board?
Results of `yarp name list` were bellow. 

```
registration name /athletebot ip 192.168.1.67 port 10000 type tcp
registration name /athletebot/torso/command:i ip 192.168.2.24 port 10010 type tcp
registration name /athletebot/torso/rpc:i ip 192.168.2.24 port 10009 type tcp
registration name /athletebot/torso/simpleclient/command:o ip 192.168.1.67 port 10015 type tcp
registration name /athletebot/torso/simpleclient/rpc:o ip 192.168.1.67 port 10014 type tcp
registration name /athletebot/torso/simpleclient/state:i ip 192.168.1.67 port 10016 type tcp
registration name /athletebot/torso/simpleclient/stateExt:i ip 192.168.1.67 port 10017 type tcp
registration name /athletebot/torso/state:o ip 192.168.2.24 port 10011 type tcp
registration name /athletebot/torso/stateExt:o ip 192.168.2.24 port 10012 type tcp
registration name /bbb ip 192.168.2.24 port 10002 type tcp
registration name /group/quit ip 192.168.2.24 port 10013 type tcp
registration name fallback ip 224.2.1.1 port 10000 type mcast
```

**Comment by iron76** [comment]
It should be the first value in the port `/athletebot/torso/state:o`. You can either use:

```
yarp read ... /athletebot/torso/state:o
```

or if you managed to compile the yarp-QT applications you can also launch the `yarpscope` as follows:

```
yarpscope --remote /athletebot/torso/state:o
```

**Comment by kzts** [comment]
Thank you! I could read analog value!

I tested on the BeagleBone you used.
Should I use other BeagleBone for testing?

**Comment by iron76** [comment]
That's a great news! Well next test would be to check that you can read multiple potentiometers and you can command multiple voltage outputs. If you want to try I think it would be very useful. I never tried more than a single potentiometers and voltage output.

**Comment by kzts** [comment]
I want to try to read multiple potentio meters and to command multiple voltage outputs.
Please could you tell me the way for it?

**Comment by iron76** [comment]
As I said I never tried but it should work by simply connecting the potentiometers and reading the correct voltage output. Potentiometers should be available in other entries of the vector streamed in the port `/athletebot/torso/state:o`. The voltage output instead should be modified with the `simpleClient` (see above) with commands like `set out joint 50` where `joint = 0 ... 7` is the output channel that you want to modify. The relevant code is in here (https://github.com/iron76/beaglebone-black-yarp/blob/gpio_from_config_file/src/modules/athleteInterface/src/BeagleBoneInputOutput.cpp) and it is substantially the code that you gave me. However I never tried channels different from `0`. If something is not working you can either try to debug the code or to wait until I am coming back to Todai.
